# stopped triggering for some reason
name: CD
on:
  release:
    branches: [master]
    types: [created, edited]

jobs:
  # todo: remove once cd workflow started triggering.
  pack-packages:
    runs-on: ubuntu-latest
    needs: pre-release
    steps:
      - uses: actions/setup-dotnet@v1.7.2
        with: { dotnet-version: '5.0' }

      - uses: actions/download-artifact@v2.0.9
        with:
          name: release-binaries

      - uses: actions/cache@v2.1.5
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: pack
        run: |
          NUGET_VERSION=${VERSION}-prerelease
          # it cannot find csproj files for some reason
          find . -name *.csproj |
          xargs -i dotnet pack -p:PackageVersion=${NUGET_VERSION} --include-source --include-symbols -p:SymbolPackageFormat=snupkg -o packages -c Release --no-restore --no-build --no-dependencies -v n {}

      - uses: actions/upload-artifact@v2.2.3
        with:
          name: release-packages
          path: |
            packages/*.nupkg
            packages/*.snupkg
          retention-days: 30

  # todo: remove once cd workflow started triggering.
  publish-packages:
    runs-on: ubuntu-latest
    needs: pack-packages
    steps:
      - uses: actions/setup-dotnet@v1.7.2
        with: { dotnet-version: '5.0' }

      - uses: actions/download-artifact@v2.0.9
        with:
          name: release-packages

      - name: publish
        run: |
          API_KEY=${{ secrets.NUGET_API_KEY }}
          find packages -name '*.nupkg' |
          xargs -i dotnet nuget push -k ${API_KEY} -s https://api.nuget.org/v3/index.json -t 30 {}
