# stopped triggering for some reason
name: CD
on:
  release:
    branches: [develop, master]
    types: [created, edited]

jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-dotnet@v1.7.2
        with: { dotnet-version: '5.0' }

      - uses: actions/download-artifact@v2.0.9
        with:
          name: release-artifacts

      - name: pack
        run: |
          VERSION=${{ github.event.release.tag_name }}
          NUGET_VERSION=$([ '${{ github.event.release.prerelease }}' == 'true' ] && echo ${VERSION}-prerelease || echo ${VERSION} )
          find . -name *.csproj | \
          xargs -i dotnet pack -p:PackageVersion=${NUGET_VERSION} -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg -o packages -c Release --no-restore --no-build --no-dependencies -v n

      - name: publish
        run: |
          API_KEY=${{ secrets.NUGET_API_KEY }}
          find . -name '*.nupkg' | 
          xargs -i dotnet nuget push -k ${API_KEY} -s https://api.nuget.org/v3/index.json -t 30 {}
          #dotnet nuget push *.nupkg -k ${API_KEY} -s https://api.nuget.org/v3/index.json -t 30

      - uses: actions/upload-artifact@v2.2.3
        with:
          name: packages
          path: |
            **/*.nupkg
            **/*.snupkg
          retention-days: 30
