name: CI/CD
on:
  push:
    branches: [master]
    paths:
      - .github/workflows/ci-cd.yml
      - src/**
      - tests/**
      - assistant.net.sln
      - LICENSE
env:
  VERSION: '${{ secrets.MAJOR_MINOR_VERSION }}.${{ github.run_number }}'

jobs:
  change-detect:
    runs-on: ubuntu-latest
    if: github.event.commits[0].id != '' # to avoid failures if no commit push (e.g. rebasing).
    steps:
      - uses: actions/checkout@v2.3.4
        with: { fetch-depth: 100 }

      - name: detect code changes
        id: change-detected
        run: |
          CHANGES=$(git diff --name-only ${{ github.event.commits[0].id }}~1..${{ github.event.after }})
          echo ::set-output name=ci-changes::echo ::set-output name=ci-changes::$(echo "$CHANGES" | grep -c -E '\.(cs|csproj|json)$')
          echo ::set-output name=core::$(echo "$CHANGES" | grep -c src/Core/)
          echo ::set-output name=core-mongo::$(echo "$CHANGES" | grep -c src/Core.Mongo/)
          echo ::set-output name=core-sqlite::$(echo "$CHANGES" | grep -c src/Core.Sqlite/)
          echo ::set-output name=core-mongo-healthcheck::$(echo "$CHANGES" | grep -c src/Core.Mongo.HealthCheck/)
          echo ::set-output name=core-sqlite-healthcheck::$(echo "$CHANGES" | grep -c src/Core.Sqlite.HealthCheck/)
          echo ::set-output name=serialization-json::$(echo "$CHANGES" | grep -c src/Serialization.Json/)
          echo ::set-output name=storage::$(echo "$CHANGES" | grep -c src/Storage/)
          echo ::set-output name=storage-mongo::$(echo "$CHANGES" | grep -c src/Storage.Mongo/)
          echo ::set-output name=storage-sqlite::$(echo "$CHANGES" | grep -c src/Storage.Sqlite/)
          echo ::set-output name=diagnostics::$(echo "$CHANGES" | grep -c src/Diagnostics/)
          echo ::set-output name=logging::$(echo "$CHANGES" | grep -c src/Logging/)
          echo ::set-output name=messaging::$(echo "$CHANGES" | grep -c src/Messaging/)
          echo ::set-output name=web-client::$(echo "$CHANGES" | grep -c src/Messaging.Web.Client/)
          echo ::set-output name=web-server::$(echo "$CHANGES" | grep -c src/Messaging.Web.Server/)
          echo ::set-output name=mongo-client::$(echo "$CHANGES" | grep -c src/Messaging.Mongo.Client/)
          echo ::set-output name=mongo-server::$(echo "$CHANGES" | grep -c src/Messaging.Mongo.Server/)
          echo ::set-output name=sqlite-client::$(echo "$CHANGES" | grep -c src/Messaging.Sqlite.Client/)
          echo ::set-output name=sqlite-server::$(echo "$CHANGES" | grep -c src/Messaging.Sqlite.Server/)
          echo ::set-output name=generic-client::$(echo "$CHANGES" | grep -c src/Messaging.Generic.Client/)
          echo ::set-output name=generic-server::$(echo "$CHANGES" | grep -c src/Messaging.Generic.Server/)
          echo ::set-output name=total::$(echo "$CHANGES" | wc -l)
    outputs:
      ci-changes: ${{ steps.change-detected.outputs.ci-changes }}
      core: ${{ steps.change-detected.outputs.core }}
      core-mongo: ${{ steps.change-detected.outputs.core-mongo }}
      core-sqlite: ${{ steps.change-detected.outputs.core-sqlite }}
      core-mongo-healthcheck: ${{ steps.change-detected.outputs.core-mongo-healthcheck }}
      core-sqlite-healthcheck: ${{ steps.change-detected.outputs.core-sqlite-healthcheck }}
      serialization-json: ${{ steps.change-detected.outputs.serialization-json }}
      storage: ${{ steps.change-detected.outputs.storage }}
      storage-mongo: ${{ steps.change-detected.outputs.storage-mongo }}
      storage-sqlite: ${{ steps.change-detected.outputs.storage-sqlite }}
      diagnostics: ${{ steps.change-detected.outputs.diagnostics }}
      logging: ${{ steps.change-detected.outputs.logging }}
      messaging: ${{ steps.change-detected.outputs.messaging }}
      web-client: ${{ steps.change-detected.outputs.web-client }}
      web-server: ${{ steps.change-detected.outputs.web-server }}
      mongo-client: ${{ steps.change-detected.outputs.mongo-client }}
      mongo-server: ${{ steps.change-detected.outputs.mongo-server }}
      sqlite-client: ${{ steps.change-detected.outputs.sqlite-client }}
      sqlite-server: ${{ steps.change-detected.outputs.sqlite-server }}
      generic-client: ${{ steps.change-detected.outputs.generic-client }}
      generic-server: ${{ steps.change-detected.outputs.generic-server }}
      total: ${{ steps.change-detected.outputs.total }}

  build:
    runs-on: ubuntu-latest
    needs: change-detect
    if: needs.change-detect.outputs.ci-changes != '0'
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-dotnet@v1.7.2
        with: { dotnet-version: '7.0' }

      - name: restore (prepare)
        uses: actions/cache@v2.1.5
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: restore
        run: dotnet restore assistant.net.sln -v n
      - name: build
        run: dotnet build assistant.net.sln -p:Version=${{ env.VERSION }} -c Release --no-restore -v n
      - name: test
        run: dotnet test assistant.net.sln -v n -c Release --no-restore --no-build -l junit -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
      - name: publish test result
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: |
            **/TestResults.xml
        if: always()
      - name: publish coverage result
        uses: codecov/codecov-action@v1.5.0
        with:
          files: |
            **/coverage.opencover.xml
        if: always()
      - name: upload result
        uses: actions/upload-artifact@v2.2.3
        with:
          name: ci-results
          path: |
            **/TestResults.xml
            **/coverage.opencover.xml
          retention-days: 60
        if: always()

      - name: upload binaries (prepare license)
        run: |
          mkdir release-binaries
          cp LICENSE release-binaries
        if: needs.change-detect.outputs.ci-changes != '0'
      - name: upload binaries
        run: cp -r src release-binaries/src
        if: needs.change-detect.outputs.ci-changes != '0'
      - name: upload binaries (prepare package counter)
        id: count-changes
        run: echo ::set-output name=total-package-prepared-count::$(ls release-binaries/src | wc -l)
      - name: upload binaries
        uses: actions/upload-artifact@v2.2.3
        with:
          name: release-binaries
          path: |
            release-binaries/**/*.csproj
            release-binaries/**/*.xml
            release-binaries/**/*.dll
            release-binaries/**/*.pdb
            release-binaries/**/*.json
            !release-binaries/**/obj/**/*.dll
            !release-binaries/**/obj/**/*.pdb
            release-binaries/LICENSE
          retention-days: 7

      # it duplicates actions/upload-artifact
      # todo: remove once actions/download-artifact supports cross workflow artifacts.
      # https://github.com/actions/toolkit/pull/517
      - name: upload binaries (workaround)
        uses: actions/cache@v2.1.5
        with:
          path: release-binaries
          key: ${{ runner.os }}-release-binaries-${{ env.VERSION }}

    outputs:
      total-package-prepared-count: ${{ steps.count-changes.outputs.total-package-prepared-count }}

  pre-release:
    runs-on: ubuntu-latest
    needs: [change-detect, build]
    # ensure the artifact were created to skip empty releases.
    if: needs.build.outputs.total-package-prepared-count != '0'
    steps:
      - name: create release (ensure binaries)
        uses: actions/download-artifact@v2.0.9
        with:
          name: release-binaries

      - name: create release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Assistant.NET Release ${{ env.VERSION }}
          prerelease: true
          draft: true # published event isn't triggered automatically, so release is created as draft to publish manually.
          body: |
            Changed files: ${{ needs.change-detect.outputs.total }}
            Packed projects: ${{ needs.build.outputs.total-package-prepared-count }}
            <details>
              <summary>Package changes</summary>
              <ul>
                <li>Core: ${{ needs.change-detect.outputs.core }}</li>
                <li>Core.Mongo: ${{ needs.change-detect.outputs.core-mongo }}</li>
                <li>Core.Sqlite: ${{ needs.change-detect.outputs.core-sqlite }}</li>
                <li>Core.Mongo.HealthCheck: ${{ needs.change-detect.outputs.core-mongo-healthcheck }}</li>
                <li>Core.Sqlite.HealthCheck: ${{ needs.change-detect.outputs.core-sqlite-healthcheck }}</li>
                <li>Serialization.Json: ${{ needs.change-detect.outputs.serialization-json }}</li>
                <li>Storage: ${{ needs.change-detect.outputs.storage }}</li>
                <li>Storage.Mongo: ${{ needs.change-detect.outputs.storage-mongo }}</li>
                <li>Storage.Sqlite: ${{ needs.change-detect.outputs.storage-sqlite }}</li>
                <li>Diagnostics: ${{ needs.change-detect.outputs.diagnostics }}</li>
                <li>Logging: ${{ needs.change-detect.outputs.logging }}</li>
                <li>Messaging: ${{ needs.change-detect.outputs.messaging }}</li>
                <li>Messaging.Web.Client: ${{ needs.change-detect.outputs.web-client }}</li>
                <li>Messaging.Web.Server: ${{ needs.change-detect.outputs.web-server }}</li>
                <li>Messaging.Mongo.Client: ${{ needs.change-detect.outputs.mongo-client }}</li>
                <li>Messaging.Mongo.Server: ${{ needs.change-detect.outputs.mongo-server }}</li>
                <li>Messaging.Sqlite.Client: ${{ needs.change-detect.outputs.sqlite-client }}</li>
                <li>Messaging.Sqlite.Server: ${{ needs.change-detect.outputs.sqlite-server }}</li>
                <li>Messaging.Generic.Client: ${{ needs.change-detect.outputs.generic-client }}</li>
                <li>Messaging.Generic.Server: ${{ needs.change-detect.outputs.generic-server }}</li>
              </ul>
            </details>
            <details>
              <summary>Commits</summary>
              <ul>
                <li>${{ join(github.event.commits.*.message, '</li><li>') }}</li>
              </ul>
            </details>
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
