name: Publish Assistant.Net packages
on:
  release:
    types: [created]
jobs:
  package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['5.0']
    steps:
      # - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
      - run: ls src/Core -R
      - uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
          source-url: https://nuget.pkg.github.com/iotbusters/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      #- run: dotnet pack -c release --no-restore --no-build src/Core/Core.csproj -v n
      #- run: dotnet nuget push src/Core/bin/Release/*.nupkg